### ISSUE TITLE
Error Message

### ISSUE THREAD

**Issue by PainSeeker419** [Llama-Logic/PlumbBuddy-Pages#10]
Log Name:      Application
Source:        Microsoft-Windows-AppModel-State
Date:          12/18/2024 2:27:49 PM
Event ID:      10
Task Category: None
Level:         Error
Keywords:      
User:          GLITTER\tkd04
Computer:      Glitter
Description:
Failure to load the application settings for package com.llamalogic.plumbbuddy_nfaajcfysheeg. Error Code: -2147024894
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Microsoft-Windows-AppModel-State" Guid="{bff15e13-81bf-45ee-8b16-7cfead00da86}" />
    <EventID>10</EventID>
    <Version>0</Version>
    <Level>2</Level>
    <Task>0</Task>
    <Opcode>0</Opcode>
    <Keywords>0x8000000000000000</Keywords>
    <TimeCreated SystemTime="2024-12-18T20:27:49.8175819Z" />
    <EventRecordID>3415</EventRecordID>
    <Correlation />
    <Execution ProcessID="9136" ThreadID="1708" />
    <Channel>Application</Channel>
    <Computer>Glitter</Computer>
    <Security UserID="S-1-5-21-726984101-3271133310-1727101457-1001" />
  </System>
  <EventData>
    <Data Name="ErrorString">com.llamalogic.plumbbuddy_nfaajcfysheeg</Data>
    <Data Name="Error">-2147024894</Data>
  </EventData>
</Event>

**Comment by amethystlilac** [comment]
@PainSeeker419 Hi, this is the wrong place for an error message for the PlumbBuddy app. Please send any future error reports to her: https://github.com/Llama-Logic/PlumbBuddy

I will be closing this issue, as it's not the correct place.

That being said, you should try uninstalling and reinstalling PlumbBuddy, since that's a Windows app error, not a PlumbBuddy error.

**Comment by PainSeeker419** [comment]
Sorry about that i will post there but it's saying it's missing files from the download... thanks anyways
